server:
  address: localhost
  port: 8080
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/newmurange
#    username: root
#    password: 401868
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://murange.cwaqtiv8hfne.ap-northeast-1.rds.amazonaws.com:3306/murangedb
    username: root
    password: nalgae415
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER # Swagger
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto:  validate  #  create validate update none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true # 예약어 사용 허용